/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    output reg [23:0] io_led,
    input usb_rx,
    output reg usb_tx,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [23:0] io_dip,
    output reg outled,
    input [0:0] customin,
    input [0:0] custominbackward,
    input [0:0] custominreset,
    output reg [2:0] livesled,
    output reg [2:0] levelled
  );
  
  
  
  reg rst;
  
  wire [5-1:0] M_led_strip_pixel;
  wire [1-1:0] M_led_strip_led;
  reg [1-1:0] M_led_strip_update;
  reg [24-1:0] M_led_strip_color;
  ws2812b_writer_1 led_strip (
    .clk(clk),
    .rst(rst),
    .update(M_led_strip_update),
    .color(M_led_strip_color),
    .pixel(M_led_strip_pixel),
    .led(M_led_strip_led)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_edge_dt_btn_up_out;
  reg [1-1:0] M_edge_dt_btn_up_in;
  edge_detector_3 edge_dt_btn_up (
    .clk(clk),
    .in(M_edge_dt_btn_up_in),
    .out(M_edge_dt_btn_up_out)
  );
  wire [1-1:0] M_edge_dt_btn_down_out;
  reg [1-1:0] M_edge_dt_btn_down_in;
  edge_detector_3 edge_dt_btn_down (
    .clk(clk),
    .in(M_edge_dt_btn_down_in),
    .out(M_edge_dt_btn_down_out)
  );
  wire [1-1:0] M_edge_dt_btn_mid_out;
  reg [1-1:0] M_edge_dt_btn_mid_in;
  edge_detector_3 edge_dt_btn_mid (
    .clk(clk),
    .in(M_edge_dt_btn_mid_in),
    .out(M_edge_dt_btn_mid_out)
  );
  wire [1-1:0] M_btn_cond_up_out;
  reg [1-1:0] M_btn_cond_up_in;
  button_conditioner_4 btn_cond_up (
    .clk(clk),
    .in(M_btn_cond_up_in),
    .out(M_btn_cond_up_out)
  );
  wire [1-1:0] M_btn_cond_down_out;
  reg [1-1:0] M_btn_cond_down_in;
  button_conditioner_4 btn_cond_down (
    .clk(clk),
    .in(M_btn_cond_down_in),
    .out(M_btn_cond_down_out)
  );
  wire [1-1:0] M_btn_cond_mid_out;
  reg [1-1:0] M_btn_cond_mid_in;
  button_conditioner_4 btn_cond_mid (
    .clk(clk),
    .in(M_btn_cond_mid_in),
    .out(M_btn_cond_mid_out)
  );
  wire [16-1:0] M_gameMachine_lives;
  wire [16-1:0] M_gameMachine_playerposition;
  wire [16-1:0] M_gameMachine_level;
  wire [16-1:0] M_gameMachine_slow_counter_time;
  wire [7-1:0] M_gameMachine_state_number;
  wire [16-1:0] M_gameMachine_result;
  wire [16-1:0] M_gameMachine_e1position;
  wire [16-1:0] M_gameMachine_e2position;
  wire [16-1:0] M_gameMachine_e3position;
  wire [16-1:0] M_gameMachine_e4position;
  wire [16-1:0] M_gameMachine_e5position;
  wire [16-1:0] M_gameMachine_e6position;
  wire [16-1:0] M_gameMachine_e7position;
  wire [16-1:0] M_gameMachine_e8position;
  wire [16-1:0] M_gameMachine_e9position;
  wire [16-1:0] M_gameMachine_e10position;
  wire [16-1:0] M_gameMachine_e11position;
  wire [16-1:0] M_gameMachine_e12position;
  wire [16-1:0] M_gameMachine_e13position;
  wire [16-1:0] M_gameMachine_e14position;
  wire [16-1:0] M_gameMachine_e15position;
  wire [16-1:0] M_gameMachine_e16position;
  wire [16-1:0] M_gameMachine_player_won;
  reg [1-1:0] M_gameMachine_up_button;
  reg [1-1:0] M_gameMachine_down_button;
  reg [1-1:0] M_gameMachine_middle_button;
  game_customBeta_5 gameMachine (
    .clk(clk),
    .rst(rst),
    .up_button(M_gameMachine_up_button),
    .down_button(M_gameMachine_down_button),
    .middle_button(M_gameMachine_middle_button),
    .lives(M_gameMachine_lives),
    .playerposition(M_gameMachine_playerposition),
    .level(M_gameMachine_level),
    .slow_counter_time(M_gameMachine_slow_counter_time),
    .state_number(M_gameMachine_state_number),
    .result(M_gameMachine_result),
    .e1position(M_gameMachine_e1position),
    .e2position(M_gameMachine_e2position),
    .e3position(M_gameMachine_e3position),
    .e4position(M_gameMachine_e4position),
    .e5position(M_gameMachine_e5position),
    .e6position(M_gameMachine_e6position),
    .e7position(M_gameMachine_e7position),
    .e8position(M_gameMachine_e8position),
    .e9position(M_gameMachine_e9position),
    .e10position(M_gameMachine_e10position),
    .e11position(M_gameMachine_e11position),
    .e12position(M_gameMachine_e12position),
    .e13position(M_gameMachine_e13position),
    .e14position(M_gameMachine_e14position),
    .e15position(M_gameMachine_e15position),
    .e16position(M_gameMachine_e16position),
    .player_won(M_gameMachine_player_won)
  );
  wire [7-1:0] M_test_display_seg;
  wire [4-1:0] M_test_display_sel;
  reg [16-1:0] M_test_display_values;
  multi_seven_seg_6 test_display (
    .clk(clk),
    .rst(rst),
    .values(M_test_display_values),
    .seg(M_test_display_seg),
    .sel(M_test_display_sel)
  );
  
  wire [16-1:0] M_converter_out;
  reg [16-1:0] M_converter_pp;
  reg [16-1:0] M_converter_lives;
  reg [16-1:0] M_converter_level;
  converter_7 converter (
    .pp(M_converter_pp),
    .lives(M_converter_lives),
    .level(M_converter_level),
    .out(M_converter_out)
  );
  
  wire [768-1:0] M_entities_hand_out;
  reg [16-1:0] M_entities_hand_playerposition;
  reg [16-1:0] M_entities_hand_e6position;
  reg [16-1:0] M_entities_hand_e11position;
  reg [16-1:0] M_entities_hand_e16position;
  reg [16-1:0] M_entities_hand_playerwon;
  reg [16-1:0] M_entities_hand_lives_left;
  entities_handler_8 entities_hand (
    .playerposition(M_entities_hand_playerposition),
    .e6position(M_entities_hand_e6position),
    .e11position(M_entities_hand_e11position),
    .e16position(M_entities_hand_e16position),
    .playerwon(M_entities_hand_playerwon),
    .lives_left(M_entities_hand_lives_left),
    .out(M_entities_hand_out)
  );
  
  wire [3-1:0] M_lives_and_levels_handler_livesled_out;
  wire [3-1:0] M_lives_and_levels_handler_levelled_out;
  reg [2-1:0] M_lives_and_levels_handler_lives;
  reg [2-1:0] M_lives_and_levels_handler_level;
  lives_and_levels_9 lives_and_levels_handler (
    .lives(M_lives_and_levels_handler_lives),
    .level(M_lives_and_levels_handler_level),
    .livesled_out(M_lives_and_levels_handler_livesled_out),
    .levelled_out(M_lives_and_levels_handler_levelled_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    io_seg = 8'hff;
    io_sel = 4'hf;
    usb_tx = usb_rx;
    io_led = 24'h000000;
    io_led[0+7-:8] = {M_gameMachine_slow_counter_time[0+7-:8]};
    io_led[8+7-:8] = {M_gameMachine_e14position[15+0-:1], M_gameMachine_e15position[15+0-:1], M_gameMachine_e8position[15+0-:1], M_gameMachine_e7position[15+0-:1], M_gameMachine_e16position[15+0-:1], M_gameMachine_e3position[15+0-:1], M_gameMachine_e2position[15+0-:1], M_gameMachine_e1position[15+0-:1]};
    io_led[16+7-:8] = {M_gameMachine_e12position[15+0-:1], M_gameMachine_e13position[15+0-:1], M_gameMachine_e11position[15+0-:1], M_gameMachine_e10position[15+0-:1], M_gameMachine_e6position[15+0-:1], M_gameMachine_e5position[15+0-:1], M_gameMachine_e4position[15+0-:1], M_gameMachine_e9position[15+0-:1]};
    M_btn_cond_up_in = customin[0+0-:1];
    M_btn_cond_down_in = custominbackward[0+0-:1];
    M_btn_cond_mid_in = custominreset[0+0-:1];
    M_edge_dt_btn_up_in = M_btn_cond_up_out;
    M_edge_dt_btn_down_in = M_btn_cond_down_out;
    M_edge_dt_btn_mid_in = M_btn_cond_mid_out;
    M_gameMachine_up_button = M_edge_dt_btn_up_out;
    M_gameMachine_down_button = M_edge_dt_btn_down_out;
    M_gameMachine_middle_button = M_edge_dt_btn_mid_out;
    M_lives_and_levels_handler_lives = M_gameMachine_lives[0+1-:2];
    M_lives_and_levels_handler_level = M_gameMachine_level[0+1-:2];
    livesled = M_lives_and_levels_handler_livesled_out;
    levelled = M_lives_and_levels_handler_levelled_out;
    io_seg = ~M_test_display_seg;
    M_converter_pp = M_gameMachine_playerposition;
    M_converter_lives = M_gameMachine_lives;
    M_converter_level = M_gameMachine_level;
    M_test_display_values = M_converter_out;
    io_sel = ~M_test_display_sel;
    M_entities_hand_e6position = M_gameMachine_e6position;
    M_entities_hand_e16position = M_gameMachine_e16position;
    M_entities_hand_e11position = M_gameMachine_e11position;
    M_entities_hand_playerposition = M_gameMachine_playerposition;
    M_entities_hand_lives_left = M_gameMachine_lives;
    M_entities_hand_playerwon = M_gameMachine_player_won;
    M_led_strip_color = M_entities_hand_out[(M_led_strip_pixel)*24+23-:24];
    M_led_strip_update = 1'h1;
    outled = M_led_strip_led;
  end
endmodule
