/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     PIXEL_COUNT = 32
*/
module led_driver_1 (
    input clk,
    input rst,
    input update,
    input [63:0] entities,
    output reg [4:0] pixel,
    output reg led
  );
  
  localparam PIXEL_COUNT = 6'h20;
  
  
  localparam SEND_PIXEL_state = 1'd0;
  localparam RESET_state = 1'd1;
  
  reg M_state_d, M_state_q = SEND_PIXEL_state;
  reg [4:0] M_pixel_ctr_d, M_pixel_ctr_q = 1'h0;
  reg [4:0] M_bit_ctr_d, M_bit_ctr_q = 1'h0;
  reg [5:0] M_ctr_d, M_ctr_q = 1'h0;
  reg [12:0] M_rst_ctr_d, M_rst_ctr_q = 1'h0;
  reg [23:0] M_color_bits_d, M_color_bits_q = 1'h0;
  
  localparam RED = 8'hff;
  
  localparam BLUE = 16'hff00;
  
  localparam PURPLE = 16'hffff;
  
  localparam OFF = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    M_ctr_d = M_ctr_q;
    M_bit_ctr_d = M_bit_ctr_q;
    M_color_bits_d = M_color_bits_q;
    M_rst_ctr_d = M_rst_ctr_q;
    M_pixel_ctr_d = M_pixel_ctr_q;
    
    led = 1'h0;
    pixel = M_pixel_ctr_q;
    
    case (M_state_q)
      SEND_PIXEL_state: begin
        
        case (entities[(M_pixel_ctr_q)*2+1-:2])
          1'h0: begin
            M_color_bits_d = 1'h0;
          end
          1'h1: begin
            M_color_bits_d = 16'hffff;
          end
          2'h2: begin
            M_color_bits_d = 16'hff00;
          end
          2'h3: begin
            M_color_bits_d = 8'hff;
          end
        endcase
        if (M_color_bits_q[(M_bit_ctr_q)*1+0-:1]) begin
          led = M_ctr_q < 7'h50;
        end else begin
          led = M_ctr_q < 6'h28;
        end
        M_ctr_d = M_ctr_q + 1'h1;
        if (M_ctr_q == 7'h7d) begin
          M_ctr_d = 1'h0;
          M_bit_ctr_d = M_bit_ctr_q + 1'h1;
          if (M_bit_ctr_q == 5'h17) begin
            M_bit_ctr_d = 1'h0;
            M_pixel_ctr_d = M_pixel_ctr_q + 1'h1;
            if (M_pixel_ctr_q == 7'h1f) begin
              M_pixel_ctr_d = 1'h0;
              M_state_d = RESET_state;
            end
          end
        end
      end
      RESET_state: begin
        if ((&M_rst_ctr_q)) begin
          if (update) begin
            M_rst_ctr_d = 1'h0;
            M_state_d = SEND_PIXEL_state;
          end
        end else begin
          M_rst_ctr_d = M_rst_ctr_q + 1'h1;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pixel_ctr_q <= 1'h0;
      M_bit_ctr_q <= 1'h0;
      M_ctr_q <= 1'h0;
      M_rst_ctr_q <= 1'h0;
      M_color_bits_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_pixel_ctr_q <= M_pixel_ctr_d;
      M_bit_ctr_q <= M_bit_ctr_d;
      M_ctr_q <= M_ctr_d;
      M_rst_ctr_q <= M_rst_ctr_d;
      M_color_bits_q <= M_color_bits_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
