/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module game_CU_12 (
    input clk,
    input rst,
    input fast_counter,
    input slow_counter,
    input forward_pressed,
    input backward_pressed,
    input reset_pressed,
    input [15:0] rb_data,
    output reg [5:0] control_sig_alufn,
    output reg [1:0] control_sig_asel,
    output reg [1:0] control_sig_bsel,
    output reg control_sig_write_enable,
    output reg [4:0] control_sig_ra,
    output reg [4:0] control_sig_rb,
    output reg [4:0] control_sig_rc,
    output reg [1:0] control_sig_wdsel,
    output reg [6:0] state_number,
    output reg [15:0] result
  );
  
  
  
  localparam IDLE_game_fsm = 7'd0;
  localparam CHECK_PP_game_fsm = 7'd1;
  localparam PP_PLUS_game_fsm = 7'd2;
  localparam PP_MINUS_game_fsm = 7'd3;
  localparam BRANCH_PP_game_fsm = 7'd4;
  localparam CHECKPP_EQ_E1_game_fsm = 7'd5;
  localparam CHECKPP_EQ_E2_game_fsm = 7'd6;
  localparam CHECKPP_EQ_E3_game_fsm = 7'd7;
  localparam CHECKPP_EQ_E4_game_fsm = 7'd8;
  localparam CHECKPP_EQ_E5_game_fsm = 7'd9;
  localparam CHECKPP_EQ_E6_game_fsm = 7'd10;
  localparam CHECKPP_EQ_E7_game_fsm = 7'd11;
  localparam CHECKPP_EQ_E8_game_fsm = 7'd12;
  localparam CHECKPP_EQ_E9_game_fsm = 7'd13;
  localparam CHECKPP_EQ_E10_game_fsm = 7'd14;
  localparam CHECKPP_EQ_E11_game_fsm = 7'd15;
  localparam CHECKPP_EQ_E12_game_fsm = 7'd16;
  localparam CHECKPP_EQ_E13_game_fsm = 7'd17;
  localparam CHECKPP_EQ_E14_game_fsm = 7'd18;
  localparam CHECKPP_EQ_E15_game_fsm = 7'd19;
  localparam CHECKPP_EQ_E16_game_fsm = 7'd20;
  localparam BRANCH_PP_EQ_E1_game_fsm = 7'd21;
  localparam BRANCH_PP_EQ_E2_game_fsm = 7'd22;
  localparam BRANCH_PP_EQ_E3_game_fsm = 7'd23;
  localparam BRANCH_PP_EQ_E4_game_fsm = 7'd24;
  localparam BRANCH_PP_EQ_E5_game_fsm = 7'd25;
  localparam BRANCH_PP_EQ_E6_game_fsm = 7'd26;
  localparam BRANCH_PP_EQ_E7_game_fsm = 7'd27;
  localparam BRANCH_PP_EQ_E8_game_fsm = 7'd28;
  localparam BRANCH_PP_EQ_E9_game_fsm = 7'd29;
  localparam BRANCH_PP_EQ_E10_game_fsm = 7'd30;
  localparam BRANCH_PP_EQ_E11_game_fsm = 7'd31;
  localparam BRANCH_PP_EQ_E12_game_fsm = 7'd32;
  localparam BRANCH_PP_EQ_E13_game_fsm = 7'd33;
  localparam BRANCH_PP_EQ_E14_game_fsm = 7'd34;
  localparam BRANCH_PP_EQ_E15_game_fsm = 7'd35;
  localparam BRANCH_PP_EQ_E16_game_fsm = 7'd36;
  localparam CHECK_END_REACHED_game_fsm = 7'd37;
  localparam BRANCH_END_REACHED_game_fsm = 7'd38;
  localparam CHECK_NEXTLVL_EXISTS_game_fsm = 7'd39;
  localparam BRANCH_NEXT_LVL_EXISTS_game_fsm = 7'd40;
  localparam WIN_game_fsm = 7'd41;
  localparam CURRENT_LVL_PLUS_game_fsm = 7'd42;
  localparam NEXT_LVL_PP_game_fsm = 7'd43;
  localparam RESET_PP_game_fsm = 7'd44;
  localparam RESET_STOP_GAME_game_fsm = 7'd45;
  localparam RESET_FAST_COUNTER_game_fsm = 7'd46;
  localparam RESET_SLOW_COUNTER_game_fsm = 7'd47;
  localparam RESET_LIVES_game_fsm = 7'd48;
  localparam RESET_LVL_game_fsm = 7'd49;
  localparam CHECK_STOP_GAME_game_fsm = 7'd50;
  localparam BRANCH_STOP_GAME_game_fsm = 7'd51;
  localparam SLOW_COUNTER_PLUS_game_fsm = 7'd52;
  localparam FAST_COUNTER_PLUS_game_fsm = 7'd53;
  localparam CHECK_LVL_EQ_3_game_fsm = 7'd54;
  localparam BRANCH_LVL_EQ_3_game_fsm = 7'd55;
  localparam CHECK_LVL_EQ_2_game_fsm = 7'd56;
  localparam BRANCH_LVL_EQ_2_game_fsm = 7'd57;
  localparam CHECK_FAST_COUNTER_MOD_3_game_fsm = 7'd58;
  localparam BRANCH_FAST_COUNTER_MOD_3_game_fsm = 7'd59;
  localparam CHECK_FAST_COUNTER_MOD_2_game_fsm = 7'd60;
  localparam BRANCH_FAST_COUNTER_MOD_2_game_fsm = 7'd61;
  localparam BLINK_E1_game_fsm = 7'd62;
  localparam BLINK_E2_game_fsm = 7'd63;
  localparam BLINK_E3_game_fsm = 7'd64;
  localparam BLINK_E4_game_fsm = 7'd65;
  localparam BLINK_E5_game_fsm = 7'd66;
  localparam BLINK_E6_game_fsm = 7'd67;
  localparam BLINK_E7_game_fsm = 7'd68;
  localparam BLINK_E8_game_fsm = 7'd69;
  localparam BLINK_E9_game_fsm = 7'd70;
  localparam BLINK_E10_game_fsm = 7'd71;
  localparam BLINK_E11_game_fsm = 7'd72;
  localparam BLINK_E12_game_fsm = 7'd73;
  localparam BLINK_E13_game_fsm = 7'd74;
  localparam BLINK_E14_game_fsm = 7'd75;
  localparam BLINK_E15_game_fsm = 7'd76;
  localparam BLINK_E16_game_fsm = 7'd77;
  localparam CHECK_LIVES_MORE_THAN_1_game_fsm = 7'd78;
  localparam BRANCH_LIVES_MORE_THAN_1_game_fsm = 7'd79;
  localparam LIVES_MINUS_game_fsm = 7'd80;
  localparam LOSE_game_fsm = 7'd81;
  localparam LOSE_LIVES_game_fsm = 7'd82;
  localparam RESPAWN_PP_game_fsm = 7'd83;
  localparam TEMP_STATE_game_fsm = 7'd84;
  localparam RESET_E1_game_fsm = 7'd85;
  localparam RESET_E2_game_fsm = 7'd86;
  localparam RESET_E3_game_fsm = 7'd87;
  localparam RESET_E4_game_fsm = 7'd88;
  localparam RESET_E5_game_fsm = 7'd89;
  localparam RESET_E6_game_fsm = 7'd90;
  localparam RESET_E7_game_fsm = 7'd91;
  localparam RESET_E8_game_fsm = 7'd92;
  localparam RESET_E9_game_fsm = 7'd93;
  localparam RESET_E10_game_fsm = 7'd94;
  localparam RESET_E11_game_fsm = 7'd95;
  
  reg [6:0] M_game_fsm_d, M_game_fsm_q = IDLE_game_fsm;
  
  reg done;
  
  always @* begin
    M_game_fsm_d = M_game_fsm_q;
    
    control_sig_alufn = 1'h0;
    control_sig_asel = 1'h0;
    control_sig_bsel = 1'h0;
    control_sig_write_enable = 1'h0;
    control_sig_ra = 1'h0;
    control_sig_rb = 1'h0;
    control_sig_rc = 1'h0;
    control_sig_wdsel = 1'h0;
    state_number = 7'h00;
    done = 1'h0;
    result = 1'h0;
    if (rst) begin
      
    end else begin
      
      case (M_game_fsm_q)
        IDLE_game_fsm: begin
          state_number = 7'h01;
          control_sig_write_enable = 1'h0;
          if (fast_counter) begin
            M_game_fsm_d = FAST_COUNTER_PLUS_game_fsm;
          end else begin
            if (slow_counter) begin
              M_game_fsm_d = CHECK_STOP_GAME_game_fsm;
            end else begin
              if (forward_pressed) begin
                M_game_fsm_d = PP_PLUS_game_fsm;
              end else begin
                if (backward_pressed) begin
                  M_game_fsm_d = CHECK_PP_game_fsm;
                end else begin
                  if (reset_pressed) begin
                    M_game_fsm_d = RESET_PP_game_fsm;
                  end else begin
                    M_game_fsm_d = IDLE_game_fsm;
                  end
                end
              end
            end
          end
        end
        FAST_COUNTER_PLUS_game_fsm: begin
          state_number = 7'h02;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h13;
          control_sig_rc = 5'h13;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = CHECK_LVL_EQ_3_game_fsm;
        end
        CHECK_LVL_EQ_3_game_fsm: begin
          state_number = 7'h03;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h3;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h12;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_LVL_EQ_3_game_fsm;
        end
        BRANCH_LVL_EQ_3_game_fsm: begin
          state_number = 7'h04;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = BLINK_E1_game_fsm;
          end else begin
            M_game_fsm_d = CHECK_LVL_EQ_2_game_fsm;
          end
        end
        CHECK_LVL_EQ_2_game_fsm: begin
          state_number = 7'h05;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h3;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h12;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_LVL_EQ_2_game_fsm;
        end
        BRANCH_LVL_EQ_2_game_fsm: begin
          state_number = 7'h06;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_FAST_COUNTER_MOD_2_game_fsm;
          end else begin
            M_game_fsm_d = CHECK_FAST_COUNTER_MOD_3_game_fsm;
          end
        end
        CHECK_FAST_COUNTER_MOD_2_game_fsm: begin
          state_number = 7'h07;
          control_sig_alufn = 6'h07;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h3;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h13;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_FAST_COUNTER_MOD_2_game_fsm;
        end
        BRANCH_FAST_COUNTER_MOD_2_game_fsm: begin
          state_number = 7'h08;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = BLINK_E7_game_fsm;
          end else begin
            M_game_fsm_d = IDLE_game_fsm;
          end
        end
        CHECK_FAST_COUNTER_MOD_3_game_fsm: begin
          state_number = 7'h09;
          control_sig_alufn = 6'h07;
          control_sig_asel = 2'h3;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h13;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_FAST_COUNTER_MOD_3_game_fsm;
        end
        BRANCH_FAST_COUNTER_MOD_3_game_fsm: begin
          state_number = 7'h0a;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = BLINK_E12_game_fsm;
          end else begin
            M_game_fsm_d = IDLE_game_fsm;
          end
        end
        BLINK_E1_game_fsm: begin
          state_number = 7'h0b;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h01;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h01;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E2_game_fsm;
        end
        BLINK_E2_game_fsm: begin
          state_number = 7'h0c;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h02;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h02;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E3_game_fsm;
        end
        BLINK_E3_game_fsm: begin
          state_number = 7'h0d;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h03;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h03;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E4_game_fsm;
        end
        BLINK_E4_game_fsm: begin
          state_number = 7'h0e;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h04;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h04;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E5_game_fsm;
        end
        BLINK_E5_game_fsm: begin
          state_number = 7'h0f;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h05;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h05;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E6_game_fsm;
        end
        BLINK_E6_game_fsm: begin
          state_number = 7'h10;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h06;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h06;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E7_game_fsm;
        end
        BLINK_E7_game_fsm: begin
          state_number = 7'h11;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h07;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h07;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E8_game_fsm;
        end
        BLINK_E8_game_fsm: begin
          state_number = 7'h12;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h08;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h08;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E9_game_fsm;
        end
        BLINK_E9_game_fsm: begin
          state_number = 7'h13;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h09;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h09;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E10_game_fsm;
        end
        BLINK_E10_game_fsm: begin
          state_number = 7'h14;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h0a;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h0a;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E11_game_fsm;
        end
        BLINK_E11_game_fsm: begin
          state_number = 7'h15;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h0b;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h0b;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E12_game_fsm;
        end
        BLINK_E12_game_fsm: begin
          state_number = 7'h16;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h0c;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h0c;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E13_game_fsm;
        end
        BLINK_E13_game_fsm: begin
          state_number = 7'h17;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h0d;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h0d;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E14_game_fsm;
        end
        BLINK_E14_game_fsm: begin
          state_number = 7'h18;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h0e;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h0e;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E15_game_fsm;
        end
        BLINK_E15_game_fsm: begin
          state_number = 7'h19;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h0f;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h0f;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BLINK_E16_game_fsm;
        end
        BLINK_E16_game_fsm: begin
          state_number = 7'h1a;
          control_sig_alufn = 6'h14;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h10;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h10;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = CHECKPP_EQ_E1_game_fsm;
        end
        CHECKPP_EQ_E1_game_fsm: begin
          state_number = 7'h1b;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h01;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E1_game_fsm;
        end
        BRANCH_PP_EQ_E1_game_fsm: begin
          state_number = 7'h1c;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          result = rb_data;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E2_game_fsm;
          end
        end
        CHECKPP_EQ_E2_game_fsm: begin
          state_number = 7'h1d;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h02;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E2_game_fsm;
        end
        BRANCH_PP_EQ_E2_game_fsm: begin
          state_number = 7'h1e;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E3_game_fsm;
          end
        end
        CHECKPP_EQ_E3_game_fsm: begin
          state_number = 7'h1f;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h03;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E3_game_fsm;
        end
        BRANCH_PP_EQ_E3_game_fsm: begin
          state_number = 7'h20;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E4_game_fsm;
          end
        end
        CHECKPP_EQ_E4_game_fsm: begin
          state_number = 7'h21;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h04;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E4_game_fsm;
        end
        BRANCH_PP_EQ_E4_game_fsm: begin
          state_number = 7'h22;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E5_game_fsm;
          end
        end
        CHECKPP_EQ_E5_game_fsm: begin
          state_number = 7'h23;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h05;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E5_game_fsm;
        end
        BRANCH_PP_EQ_E5_game_fsm: begin
          state_number = 7'h24;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E6_game_fsm;
          end
        end
        CHECKPP_EQ_E6_game_fsm: begin
          state_number = 7'h25;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 4'h6;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E6_game_fsm;
        end
        BRANCH_PP_EQ_E6_game_fsm: begin
          state_number = 7'h26;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E7_game_fsm;
          end
        end
        CHECKPP_EQ_E7_game_fsm: begin
          state_number = 7'h27;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 4'h7;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E7_game_fsm;
        end
        BRANCH_PP_EQ_E7_game_fsm: begin
          state_number = 7'h28;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E8_game_fsm;
          end
        end
        CHECKPP_EQ_E8_game_fsm: begin
          state_number = 7'h29;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h08;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E8_game_fsm;
        end
        BRANCH_PP_EQ_E8_game_fsm: begin
          state_number = 7'h2a;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E9_game_fsm;
          end
        end
        CHECKPP_EQ_E9_game_fsm: begin
          state_number = 7'h2b;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h09;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E9_game_fsm;
        end
        BRANCH_PP_EQ_E9_game_fsm: begin
          state_number = 7'h2c;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E10_game_fsm;
          end
        end
        CHECKPP_EQ_E10_game_fsm: begin
          state_number = 7'h2d;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h0a;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E10_game_fsm;
        end
        BRANCH_PP_EQ_E10_game_fsm: begin
          state_number = 7'h2e;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E11_game_fsm;
          end
        end
        CHECKPP_EQ_E11_game_fsm: begin
          state_number = 7'h2f;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h0b;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E11_game_fsm;
        end
        BRANCH_PP_EQ_E11_game_fsm: begin
          state_number = 7'h30;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E12_game_fsm;
          end
        end
        CHECKPP_EQ_E12_game_fsm: begin
          state_number = 7'h31;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h0c;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E12_game_fsm;
        end
        BRANCH_PP_EQ_E12_game_fsm: begin
          state_number = 7'h32;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E13_game_fsm;
          end
        end
        CHECKPP_EQ_E13_game_fsm: begin
          state_number = 7'h33;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h0d;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E13_game_fsm;
        end
        BRANCH_PP_EQ_E13_game_fsm: begin
          state_number = 7'h34;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E14_game_fsm;
          end
        end
        CHECKPP_EQ_E14_game_fsm: begin
          state_number = 7'h35;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h0e;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E14_game_fsm;
        end
        BRANCH_PP_EQ_E14_game_fsm: begin
          state_number = 7'h36;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E15_game_fsm;
          end
        end
        CHECKPP_EQ_E15_game_fsm: begin
          state_number = 7'h37;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h0f;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E15_game_fsm;
        end
        BRANCH_PP_EQ_E15_game_fsm: begin
          state_number = 7'h38;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECKPP_EQ_E16_game_fsm;
          end
        end
        CHECKPP_EQ_E16_game_fsm: begin
          state_number = 7'h39;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h10;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_EQ_E16_game_fsm;
        end
        BRANCH_PP_EQ_E16_game_fsm: begin
          state_number = 7'h3a;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_LIVES_MORE_THAN_1_game_fsm;
          end else begin
            M_game_fsm_d = CHECK_END_REACHED_game_fsm;
          end
        end
        CHECK_LIVES_MORE_THAN_1_game_fsm: begin
          state_number = 7'h3b;
          control_sig_alufn = 6'h35;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h15;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_LIVES_MORE_THAN_1_game_fsm;
        end
        BRANCH_LIVES_MORE_THAN_1_game_fsm: begin
          state_number = 7'h3c;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = LIVES_MINUS_game_fsm;
          end else begin
            M_game_fsm_d = LOSE_LIVES_game_fsm;
          end
        end
        LIVES_MINUS_game_fsm: begin
          state_number = 7'h3d;
          control_sig_alufn = 6'h01;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h15;
          control_sig_rb = 5'h1b;
          control_sig_rc = 5'h15;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESPAWN_PP_game_fsm;
        end
        RESPAWN_PP_game_fsm: begin
          state_number = 7'h3e;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h1;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h1c;
          control_sig_rc = 5'h00;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = IDLE_game_fsm;
        end
        LOSE_LIVES_game_fsm: begin
          state_number = 7'h3d;
          control_sig_alufn = 6'h01;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h15;
          control_sig_rb = 5'h1b;
          control_sig_rc = 5'h15;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = LOSE_game_fsm;
        end
        LOSE_game_fsm: begin
          state_number = 7'h3f;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h1;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h16;
          control_sig_wdsel = 2'h3;
          if (reset_pressed) begin
            M_game_fsm_d = RESET_PP_game_fsm;
          end
        end
        RESET_PP_game_fsm: begin
          state_number = 7'h40;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h1;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h1c;
          control_sig_rc = 5'h00;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_STOP_GAME_game_fsm;
        end
        RESET_STOP_GAME_game_fsm: begin
          state_number = 7'h41;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h1;
          control_sig_bsel = 2'h1;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h16;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_FAST_COUNTER_game_fsm;
        end
        RESET_FAST_COUNTER_game_fsm: begin
          state_number = 7'h42;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h13;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_SLOW_COUNTER_game_fsm;
        end
        RESET_SLOW_COUNTER_game_fsm: begin
          state_number = 7'h43;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h14;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_LIVES_game_fsm;
        end
        RESET_LIVES_game_fsm: begin
          state_number = 7'h44;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h3;
          control_sig_bsel = 2'h1;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h15;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_LVL_game_fsm;
        end
        RESET_LVL_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h1;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h12;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E1_game_fsm;
        end
        RESET_E1_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h01;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h01;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E2_game_fsm;
        end
        RESET_E2_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h02;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h02;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E3_game_fsm;
        end
        RESET_E3_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h03;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h03;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E4_game_fsm;
        end
        RESET_E4_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h04;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h04;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E5_game_fsm;
        end
        RESET_E5_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h05;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h05;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E6_game_fsm;
        end
        RESET_E6_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h06;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h06;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E7_game_fsm;
        end
        RESET_E7_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h07;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h07;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E8_game_fsm;
        end
        RESET_E8_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h08;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h08;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E9_game_fsm;
        end
        RESET_E9_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h09;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h09;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E10_game_fsm;
        end
        RESET_E10_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h0a;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h0a;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = RESET_E11_game_fsm;
        end
        RESET_E11_game_fsm: begin
          state_number = 7'h45;
          control_sig_alufn = 6'h1b;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h0b;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h0b;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = IDLE_game_fsm;
        end
        PP_PLUS_game_fsm: begin
          state_number = 7'h46;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h00;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = CHECKPP_EQ_E1_game_fsm;
        end
        CHECK_PP_game_fsm: begin
          state_number = 7'h47;
          control_sig_alufn = 6'h35;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h1c;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h1f;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_PP_game_fsm;
        end
        BRANCH_PP_game_fsm: begin
          state_number = 7'h48;
          control_sig_rb = 5'h1f;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = PP_MINUS_game_fsm;
          end else begin
            M_game_fsm_d = IDLE_game_fsm;
          end
        end
        PP_MINUS_game_fsm: begin
          state_number = 7'h49;
          control_sig_alufn = 6'h01;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h1b;
          control_sig_rc = 5'h00;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = CHECKPP_EQ_E1_game_fsm;
        end
        CHECK_END_REACHED_game_fsm: begin
          state_number = 7'h4a;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h0;
          control_sig_bsel = 2'h2;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_END_REACHED_game_fsm;
        end
        BRANCH_END_REACHED_game_fsm: begin
          state_number = 7'h4b;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          result = rb_data;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = CHECK_NEXTLVL_EXISTS_game_fsm;
          end else begin
            M_game_fsm_d = IDLE_game_fsm;
          end
        end
        CHECK_NEXTLVL_EXISTS_game_fsm: begin
          state_number = 7'h4c;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h3;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h12;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_NEXT_LVL_EXISTS_game_fsm;
        end
        BRANCH_NEXT_LVL_EXISTS_game_fsm: begin
          state_number = 7'h4d;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = WIN_game_fsm;
          end else begin
            M_game_fsm_d = CURRENT_LVL_PLUS_game_fsm;
          end
        end
        CURRENT_LVL_PLUS_game_fsm: begin
          state_number = 7'h53;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h12;
          control_sig_rc = 5'h12;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = NEXT_LVL_PP_game_fsm;
        end
        TEMP_STATE_game_fsm: begin
          state_number = 7'h7f;
          control_sig_rb = 5'h0b;
          control_sig_write_enable = 1'h0;
          result = rb_data;
        end
        NEXT_LVL_PP_game_fsm: begin
          state_number = 7'h4e;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h1;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h1c;
          control_sig_rc = 5'h00;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = IDLE_game_fsm;
        end
        WIN_game_fsm: begin
          state_number = 7'h4f;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h00;
          control_sig_rc = 5'h16;
          control_sig_wdsel = 2'h0;
          if (reset_pressed) begin
            M_game_fsm_d = RESET_PP_game_fsm;
          end
        end
        CHECK_STOP_GAME_game_fsm: begin
          state_number = 7'h50;
          control_sig_alufn = 6'h33;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h16;
          control_sig_rc = 5'h17;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = BRANCH_STOP_GAME_game_fsm;
        end
        BRANCH_STOP_GAME_game_fsm: begin
          state_number = 7'h51;
          control_sig_rb = 5'h17;
          control_sig_write_enable = 1'h0;
          if (rb_data[0+0-:1] == 1'h1) begin
            M_game_fsm_d = IDLE_game_fsm;
          end else begin
            M_game_fsm_d = SLOW_COUNTER_PLUS_game_fsm;
          end
        end
        SLOW_COUNTER_PLUS_game_fsm: begin
          state_number = 7'h52;
          control_sig_alufn = 6'h00;
          control_sig_asel = 2'h2;
          control_sig_bsel = 2'h0;
          control_sig_write_enable = 1'h1;
          control_sig_ra = 5'h00;
          control_sig_rb = 5'h14;
          control_sig_rc = 5'h14;
          control_sig_wdsel = 2'h0;
          M_game_fsm_d = IDLE_game_fsm;
        end
      endcase
    end
  end
  
  always @(posedge clk) begin
    M_game_fsm_q <= M_game_fsm_d;
  end
  
endmodule
