/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module lives_and_levels_9 (
    input [1:0] lives,
    input [1:0] level,
    output reg [2:0] livesled_out,
    output reg [2:0] levelled_out
  );
  
  
  
  always @* begin
    if (lives == 2'h3) begin
      livesled_out[0+0-:1] = 1'h1;
      livesled_out[1+0-:1] = 1'h1;
      livesled_out[2+0-:1] = 1'h1;
    end else begin
      if (lives == 2'h2) begin
        livesled_out[0+0-:1] = 1'h1;
        livesled_out[1+0-:1] = 1'h1;
        livesled_out[2+0-:1] = 1'h0;
      end else begin
        if (lives == 1'h1) begin
          livesled_out[0+0-:1] = 1'h1;
          livesled_out[1+0-:1] = 1'h0;
          livesled_out[2+0-:1] = 1'h0;
        end else begin
          livesled_out[0+0-:1] = 1'h0;
          livesled_out[1+0-:1] = 1'h0;
          livesled_out[2+0-:1] = 1'h0;
        end
      end
    end
    if (level == 2'h3) begin
      levelled_out[0+0-:1] = 1'h1;
      levelled_out[1+0-:1] = 1'h1;
      levelled_out[2+0-:1] = 1'h1;
    end else begin
      if (level == 2'h2) begin
        levelled_out[0+0-:1] = 1'h1;
        levelled_out[1+0-:1] = 1'h1;
        levelled_out[2+0-:1] = 1'h0;
      end else begin
        if (level == 1'h1) begin
          levelled_out[0+0-:1] = 1'h1;
          levelled_out[1+0-:1] = 1'h0;
          levelled_out[2+0-:1] = 1'h0;
        end else begin
          levelled_out[0+0-:1] = 1'h0;
          levelled_out[1+0-:1] = 1'h0;
          levelled_out[2+0-:1] = 1'h0;
        end
      end
    end
  end
endmodule
