# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/managed_ip_project/managed_ip_project.runs/mig_7series_0_synth_1/.Xil/Vivado-16532-DESKTOP-SAE033K/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tftg256-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_mc.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_std.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0.v
      c:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0_mig.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/managed_ip_project/managed_ip_project.runs/mig_7series_0_synth_1/.Xil/Vivado-16532-DESKTOP-SAE033K/realtime/mig_7series_0_synth.xdc
    rt::sdcChecksum
    set rt::top mig_7series_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Bryan/Documents/GitHub/1DFlashQuantumTunneling/theflash/cores/managed_ip_project/managed_ip_project.runs/mig_7series_0_synth_1/.Xil/Vivado-16532-DESKTOP-SAE033K/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
